DROP TABLE IF EXISTS Writer CASCADE;
DROP TABLE IF EXISTS Blogpost;
DROP TYPE BLOGPOST_ENUM;
CREATE TYPE BLOGPOST_ENUM AS ENUM ('Technical', 'Agile');
CREATE TABLE Writer (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    surname TEXT NOT NULL,
    nickname TEXT
);
CREATE TABLE Blogpost (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    blogpost_type BLOGPOST_ENUM NOT NULL,
    writer_id SERIAL REFERENCES Writer(id)
);